
PUT http://localhost:8081/movies/123?title=Avengers
Accept: application/json

###

PUT http://localhost:8081/movies/333?title=Batman
Accept: application/json

###

PUT http://localhost:8081/movies/666?title=Avengers
Accept: application/json

###

PUT http://localhost:8081/movies/999?title=Startrek
Accept: application/json

###

GET http://localhost:8081/movies/
Accept: application/json

###

PUT http://localhost:8081/movies/999?title=Startrek
Accept: application/json

