POST http://localhost:8081/movies/123/rent?customer=andrea
Accept: application/json

###

GET http://localhost:8081/rentals
Accept: application/json

###
POST http://localhost:8081/movies/333/rent?customer=andrea
Accept: application/json

###
POST http://localhost:8081/movies/666/rent?customer=andrea
Accept: application/json

###
POST http://localhost:8081/movies/123/rent?customer=fabio
Accept: application/json

###
GET http://localhost:8081/rentals/f89fcbb2-4682-4a8b-b0ba-11d614f4962a/status
Accept: application/json






